app:
  filter: "!51spuRwZiq)pz3ajPISQFVxv)9LOZJaAo6Iueu"

spring:
  application:
    name: Scrapper
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 500
      thread-name-prefix: task-executor-
      shutdown:
        await-termination: true
        await-termination-period: 10s
    scheduling:
      pool:
        size: 2
      shutdown:
        await-termination: true
        await-termination-period: 10s

pagination:
  page-size: 100

server:
  port: 8081

logging:
  level:
    root: info
