spring:
  application:
    name: Scrapper
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true

pagination:
  page-size: 100

server:
  port: 8081

