app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-url: ${SCRAPPER_URL}
  telegram-url: "https://api.telegram.org"

features:
  webhook:
    enabled: false

logging:
  level:
    root: info

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
