features:
  webhook:
    enabled: false

logging:
  level:
    root: info

spring:
  application:
    name: Bot
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080
